clone_depth: 5
image:
  - Visual Studio 2015
environment:
  matrix:
    - target_type: x86
      vc_version: 2012
    - target_type: x64
      vc_version: 2012
    - target_type: x64_pe
      vc_version: 2012
#     - target_type: x86
#       vc_version: 2013
#     - target_type: x64
#       vc_version: 2013
#     - target_type: x64_pe
#       vc_version: 2013
#     - target_type: x86
#       vc_version: 2015
#     - target_type: x64
#       vc_version: 2015
#     - target_type: x64_pe
#       vc_version: 2015
build_script:
  - cmd /c PCbuild\my_build.bat %target_type% %vc_version%
test_script:
  - cmd /c PCbuild\my_test.bat
artifacts:
  - path: PCbuild\python*.exe
    name: python_exe
