name: Python

on:
  push:
    branches: [ master3, master3.7, support_github_actions ]
  pull_request:
    branches: [ master3, master3.7 ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target_type: x86
          vc_version: 2017
        - target_type: x64
          vc_version: 2017
        - target_type: x64_pe
          vc_version: 2017
    runs-on: windows-2016
    steps:
    - name: "Disable git autoCRLF"
      run: git config --global core.autoCRLF false
    - uses: actions/checkout@v2
    - name: Build
      run: cmd /c PCbuild\my_build.bat ${{ matrix.target_type }} ${{ matrix.vc_version }}
    - name: Test
      run: cmd /c PCbuild\my_test.bat ${{ matrix.target_type }} ${{ matrix.vc_version }}
